#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

cd "${APP_DIR}" || exit 1
# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/Ombi" --host http://0.0.0.0:5000 --storage "${CONFIG_DIR}/app" ${ARGS}
